#!/bin/bash
# Clean build artifacts and environment

set -e

echo "🧹 Cleaning up project..."

# Remove virtual environment if exists
if [ -d ".venv" ]; then
    echo "🗑️  Removing virtual environment..."
    rm -rf .venv
fi

# Remove dist build artifacts
if [ -d "dist" ]; then
    echo "🗑️  Removing build artifacts..."
    rm -rf dist
fi

# Remove cache
if [ -d ".pytest_cache" ]; then
    echo "🗑️  Removing pytest cache..."
    rm -rf .pytest_cache
fi

if [ -d "__pycache__" ]; then
    echo "🗑️  Removing __pycache__..."
    rm -rf __pycache__
fi

# Remove .coverage
if [ -f ".coverage" ]; then
    echo "🗑️  Removing coverage files..."
    rm -f .coverage
fi

echo "✅ Cleanup complete!"
echo "📝 Note: Make sure to reinstall dependencies after cleanup"



```
botChatty/
├── app.py              # Main bot application
├── __init__.py         # Package initialization
└── requirements.txt    # Dependencies
fi





tests/
├── __init__.py
└── test_app.py        # Unit tests
fi


docs/
├── README.md          # This file
├── technical.md       # Technical documentation
├── non-technical.md   # User guide
├── quick-start.md     # Getting started
└── api-reference.md   # API reference
```

## Getting Started

See the [Quick Start Guide](./quick-start.md) for installation and running instructions.

## Support

For issues or questions, please:
- Check the [Technical Documentation](./technical.md)
- Review the [API Reference](./api-reference.md)
- Create a GitHub issue

---

*Generated by Makefile documentation system*
```

```markdown
docs/technical.md
```

```markdown
# Technical Documentation - Slack Bot Chatty

## Overview

This document provides technical details for developers working on the Slack Bot Chatty project.

## Architecture

### Project Structure

```
src/botChatty/
├── __init__.py        # Package initialization
└── app.py             # Main application logic
```

### Dependencies

The bot uses the following key dependencies:

- `slack_bolt`: Slack API integration
- `python-dotenv`: Environment variable management
- `pytest`: Testing framework
- `ruff`: Linting and formatting

See `requirements.txt` for full dependency list.

## Application Flow

1. **Initialization**: Creates Slack Bolt app instance
2. **Event Registration**: Registers message handlers
3. **Error Handling**: Custom error handlers for logging
4. **Socket Mode**: Uses SocketModeHandler for local development

## Code Quality

- Linting: `ruff`
- Testing: `pytest` with coverage
- Formatting: `ruff format`
- Type hints: Not currently used (can be added)

## Testing Strategy

- Unit tests in `tests/test_app.py`
- Mock external services (Slack API)
- Test coverage tracking
- CI/CD integration with GitHub Actions

## Docker Deployment

The project includes Docker support for easy deployment:

```bash
make docker
docker run -d \
  --name bot-chatty \
  --env-file .env \
  -p 8080:8080 \
  slack-bot-chatty:latest
echo "📝 Note: Make sure to reinstall dependencies after cleanup"